### ISSUE TITLE
Blah blah

### ISSUE THREAD

**Issue by Beamanator** [Beamanator/Just-To-Learn#53]
Hello and welcome to this month's edition of *CAP software*.

## :mega: The process has changed, so please read up!

What I need from you:
1. Go to the [CAP Software spreadsheet]

**Comment by botify** [comment]
cc @kortneywynn

**Comment by botify** [comment]
cc @kortneywynn

**Comment by Beamanator** [comment]
Nice made this issue: https://github.com/Beamanator/Just-To-Learn/issues/54
